defaults: ./grpo-moonlight-16ba3b-4n8g-megatron.yaml
checkpointing:
  checkpoint_dir: results/grpo-moonlight-16ba3b-4n4g-megatron
logger:
  wandb:
    name: grpo-moonlight-16ba3b-4n4g-megatron
cluster:
  gpus_per_node: 4

