defaults: ./grpo-nano-v2-12b-1n8g-megatron.yaml
checkpointing:
  checkpoint_dir: results/grpo-nano-v2-12b-1n4g-megatron
logger:
  log_dir: logs/grpo-nano-v2-12b-1n4g-megatron
  wandb:
    name: grpo-nano-v2-12b-1n4g-megatron
cluster:
  gpus_per_node: 4

