defaults: ./grpo-qwen3-30ba3b-8n8g-megatron.yaml
policy:
  make_sequence_length_divisible_by: 2
  generation:
    vllm_cfg:
      tensor_parallel_size: 2
checkpointing:
  checkpoint_dir: results/grpo-qwen3-30ba3b-8n4g-megatron
logger:
  log_dir: logs/grpo-qwen3-30ba3b-8n4g-megatron
  wandb:
    name: grpo-qwen3-30ba3b-8n4g-megatron
cluster:
  gpus_per_node: 4

