defaults: ./grpo-deepseek-v3-64n8g-async-1off.yaml
checkpointing:
  checkpoint_dir: results/grpo-deepseek-v3-64n8g-fp8-async-1off
policy:
  generation:
    vllm_cfg:
      tensor_parallel_size: 16
      precision: "fp8"
      use_deep_gemm: true
      quantization_ignored_layer_kws: [
        a_proj,
        b_proj
      ]
    vllm_kwargs:
      max_num_seqs: 32
logger:
  log_dir: logs/grpo-deepseek-v3-64n8g-fp8-async-1off
  wandb:
    name: grpo-deepseek-v3-64n8g-fp8-async-1off
