defaults: ./grpo-deepseek-v3-32n8g.yaml
checkpointing:
  checkpoint_dir: results/grpo-deepseek-v3-32n4g
policy:
  sequence_packing:
    enabled: false
  generation:
    vllm_cfg:
      tensor_parallel_size: 32
logger:
  log_dir: logs/grpo-deepseek-v3-32n4g
  wandb:
    name: grpo-deepseek-v3-32n4g
cluster:
  gpus_per_node: 4
  num_nodes: 32
