defaults: ./grpo-llama3.1-8b-instruct-2n8g-async-1off.yaml
checkpointing:
  checkpoint_dir: results/grpo-llama3.1-8b-instruct-2n8g-fp8-async-1off
policy:
  generation:
    vllm_cfg:
      precision: "fp8"
      use_deep_gemm: true
logger:
  log_dir: logs/grpo-llama3.1-8b-instruct-2n8g-fp8-async-1off
  wandb:
    name: grpo-llama3.1-8b-instruct-2n8g-fp8-async-1off