[build-system]
requires = ["setuptools", "wheel", "toml"]
build-backend = "setuptools.build_meta"

[project]
name = "nv-one-logger-wandb"
description = "Wrapper for nv-one-logger-wandb"
requires-python = ">=3.9"
dynamic = ["version", "dependencies"]
