defaults: ../../vlm_grpo_3B.yaml
checkpointing:
  checkpoint_dir: results/clevr_grpo
policy:
  max_total_sequence_length: 3072
  dtensor_cfg:
    enabled: false
  dynamic_batching:
    enabled: false
  optimizer: null
  megatron_recipe: megatron.bridge.recipes.qwen.qwen2.qwen2_5_vl_3b_pretrain_config
logger:
  wandb:
    name: vlm-grpo-3b-megatron
cluster:
  gpus_per_node: 8
