[build-system]
requires = ["setuptools", "wheel", "toml"]
build-backend = "setuptools.build_meta"

[project]
name = "nv-one-logger-training-telemetry"
description = "Wrapper for nv-one-logger-training-telemetry"
requires-python = ">=3.8"
dynamic = ["version", "dependencies"]
