# GRPO Algorithm Configuration
defaults: "grpo_math_70B_megatron.yaml"

loss_fn:
  use_importance_sampling_correction: true

policy:
  generation:
    vllm_cfg:
      precision: "fp8"
      use_deep_gemm: true