defaults:
  - sft_vlm_3B.yaml

sft:
  val_batches: 2
  val_global_batch_size: 8

policy:
  max_total_sequence_length: 32768
  train_global_batch_size: 8
  dtensor_cfg:
    tensor_parallel_size: 1
  dynamic_batching:
    enabled: true
  tokenizer:
    video:
      num_frames: 16

data:
  dataset_name: GeneralConversationsJsonlDataset
  train_data_path: /lustre/fsw/portfolios/llmservice/users/yuanhangs/codes/megatron-lm-omcat/megatron-lm-vlm2/examples/multimodal/avlm/test/datasets/miradata_bat1_filtered_vision_5min_10000.jsonl
  val_data_path: /lustre/fsw/portfolios/llmservice/users/yuanhangs/codes/megatron-lm-omcat/megatron-lm-vlm2/examples/multimodal/avlm/test/datasets/miradata_bat1_filtered_vision_5min_100.jsonl
  train_media_data_dir: /lustre/fsw/portfolios/edgeai/projects/edgeai_riva_rivamlops/data/videomme/MiraData/video/batch1/5min
  val_media_data_dir: /lustre/fsw/portfolios/edgeai/projects/edgeai_riva_rivamlops/data/videomme/MiraData/video/batch1/5min
